service:
    name: harness_h2
    identifier: harnessOMS
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: OMS_H2
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - oms-modernized/config-files/oms-modernized-h2-deployment.yaml
                                - oms-modernized/config-files/oms-modernized-h2-svc.yaml
                            repoName: gitops
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false
