apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-inventory 
  name: oms-inventory
  namespace: fbesnard
spec:
  selector:
    app: oms-inventory 
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081