apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oms-inventory
  name: oms-inventory
  namespace: fbesnard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-inventory 
  template:
    metadata:
      labels:
        app: oms-inventory 
    spec:
      hostname: oms-inventory
      containers:
      - image: fbesnarddvt/refactoring-oms-inventory-controller:1.0
        name: oms-inventory 
        envFrom:
        - configMapRef:
            name: oms-inventory-app-config
        ports:
        - containerPort: 8080
