apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oms-h2-db
  name: oms-h2-db
  namespace: fbesnard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-h2-db
  template:
    metadata:
      labels:
        app: oms-h2-db
    spec:
      containers:
      - image: oscarfonts/h2
        name: oms-h2
        env:
        - name: H2_OPTIONS
          value: "-ifNotExists"
        ports:
        - containerPort: 81
        - containerPort: 1521