apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-order 
  name: oms-order
  namespace: fbesnard
spec:
  selector:
    app: oms-order 
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30183