apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oms-order
  name: oms-order
  namespace: fbesnard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oms-order 
  template:
    metadata:
      labels:
        app: oms-order 
    spec:
      containers:
      - image: fbesnarddvt/refactoring-oms-order-controller:1.0
        name: oms-order 
        envFrom:
        - configMapRef:
            name: oms-order-app-config
        ports:
        - containerPort: 8080
---
