apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-h2-db
  name: oms-h2-admin
  namespace: fbesnard
spec:
  selector:
    app: oms-h2-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-h2-db
  name: oms-h2-data
  namespace: fbesnard
spec:
  selector:
    app: oms-h2-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521