apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-h2-db
  name: oms-h2-admin
  namespace: fbesnard
spec:
  selector:
    app: oms-h2-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 81
    targetPort: 81
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-h2-db
  name: oms-h2-data
  namespace: fbesnard
spec:
  selector:
    app: oms-h2-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 1521
    targetPort: 1521

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-inventory 
  name: oms-inventory
  namespace: fbesnard
spec:
  selector:
    app: oms-inventory 
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-product 
  name: oms-product
  namespace: fbesnard
spec:
  selector:
    app: oms-product 
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oms-order 
  name: oms-order
  namespace: fbesnard
spec:
  selector:
    app: oms-order 
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30083